name: MLops opdracht 3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build the Docker image based on the Dockerfile.
      - name: Build Dockerfile
        run: docker build --tag ghrc.io/nathansegers/gh-actions-nginx:v1 .
       
      # If the container already runs, it must be stoppen. If it doesn't exist, ignore the error and continue the workflow.
      - name: Stop the container if it exists, ignore if it doesn't
        continue-on-error: true
        run: docker stop gh-nginx-test

      # If the container already exitst, it must be removed. If it doesn't exist, ignore the error and continue the workflow.
      - name: Remove the container if it exists, ignore if it doesn't
        continue-on-error: true
        run: docker rm gh-nginx-test
      
      # Run the Dockerfile.
      - name: Run Dockerfile
        run: |
             docker run -d -p 8010:80 --name gh-nginx-test ghrc.io/nathansegers/gh-actions-nginx:v1